# Generated by Django 4.1 on 2022-08-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_jobvacancy_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('f', 'Full-time'), ('c', 'Contract'), ('p', 'Part-time'), ('i', 'Internship')], default='f', help_text='Employee Type', max_length=1),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('en', 'Entry-Level'), ('im', 'Immediate'), ('sr', 'Senior'), ('ex', 'Expert')], default='en', help_text='Experience Level', max_length=2),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='location',
            field=models.CharField(blank=True, choices=[('r', 'Remote'), ('o', 'Onsite'), ('h', 'Hybrid')], default='r', help_text='Location', max_length=1),
        ),
        migrations.DeleteModel(
            name='EmployeeType',
        ),
        migrations.DeleteModel(
            name='ExperienceLevel',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
