# Generated by Django 4.1 on 2022-08-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_jobvacancy_employee_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('f', 'Full-time'), ('c', 'Contract'), ('p', 'Part-time'), ('i', 'Internship')], default='f', max_length=1),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('en', 'Entry-Level'), ('im', 'Immediate'), ('sr', 'Senior'), ('ex', 'Expert')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='location',
            field=models.CharField(blank=True, choices=[('r', 'Remote'), ('o', 'Onsite'), ('h', 'Hybrid')], default='r', max_length=1),
        ),
    ]
