# Generated by Django 4.1 on 2022-08-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_jobvacancy_employee_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobvacancy',
            options={'ordering': ['created', 'updated'], 'verbose_name': 'Job Vacancy', 'verbose_name_plural': 'Job Vacancies'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.CharField(max_length=255),
        ),
    ]
